version: '3'

services:
  static:
    image: minio/minio
    ports:
      - "32761:9000"
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: rooming_user
      MINIO_SECRET_KEY: rooming_password
    command: server /export
  db:
    image: postgres
    environment:
      POSTGRES_USER: rooming_user
      POSTGRES_PASSWORD: rooming_password
      POSTGRES_DB: rooming
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
  web:
    build: rooming
    restart: always
    volumes:
      - ./rooming:/code
    ports:
      - "8000"
    depends_on:
      - static
      - db
    env_file: ./rooming/.docker-env
volumes:
  postgres_data:
