# Generated by Django 2.1.3 on 2018-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181119_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_flag',
            field=models.BooleanField(default=False),
        ),
    ]
