# Generated by Django 2.1.3 on 2018-12-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181210_1628'),
        ('accounts', '0002_auto_20181210_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingurl',
            name='url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='trackingurl',
            unique_together={('account', 'user', 'url', 'live')},
        ),
    ]
