# Generated by Django 2.1.3 on 2018-11-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import lib.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Answer/質問',
                'verbose_name_plural': 'Answers/質問',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Question/質問',
                'verbose_name_plural': 'Questions/質問',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('question_answer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.Question')),
            ],
            options={
                'verbose_name': 'QuestionAnswer/質問回答回答',
                'verbose_name_plural': 'QuestionAnswers/質問回答回答',
                'db_table': 'question_answer',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_id'], name='question_questio_ae2cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answer_id'], name='answer_answer__c6782d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question'], name='question_an_questio_a1cbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['answer'], name='question_an_answer__84e3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question', 'answer'], name='question_an_questio_98f571_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('question', 'answer', 'live')},
        ),
    ]
