# Generated by Django 2.1.3 on 2018-11-18 13:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import lib.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('diagnosis_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phase', models.CharField(max_length=2000)),
                ('preface', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=8)),
            ],
            options={
                'verbose_name': 'Diagnosis/質問',
                'verbose_name_plural': 'Diagnoses/質問',
                'db_table': 'diagnosis',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='question',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='next_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='diagnoses.Question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='diagnoses.Question'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['account'], name='answer_account_8e567e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['account'], name='question_account_006bb2_idx'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='first_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.Question'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['diagnosis_id'], name='diagnosis_diagnos_1cfa25_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase'], name='diagnosis_phase_99fb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['first_question'], name='diagnosis_first_q_a1faee_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['account'], name='diagnosis_account_8d382b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase', 'account'], name='diagnosis_phase_1d42ad_idx'),
        ),
    ]
