# Generated by Django 2.1.3 on 2018-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0002_auto_20181118_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
