# Generated by Django 2.1.3 on 2018-11-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('diagnoses', '0004_auto_20181119_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['account'], name='question_an_account_fe2d77_idx'),
        ),
    ]
