# Generated by Django 2.1.3 on 2018-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0006_auto_20181204_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='note1',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='note1',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
