# Generated by Django 2.1.3 on 2018-12-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0007_auto_20181211_1529'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diagnosis',
            name='diagnosis_phase_99fb0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='diagnosis',
            name='diagnosis_phase_1d42ad_idx',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='phase',
            new_name='phase1',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='phase2',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='phase3',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase1'], name='diagnosis_phase1_7d1317_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase2'], name='diagnosis_phase2_a97b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase3'], name='diagnosis_phase3_4c4fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['phase1', 'phase2', 'phase3', 'account'], name='diagnosis_phase1_e45431_idx'),
        ),
    ]
