# Generated by Django 2.1.3 on 2018-11-08 07:56

from django.db import migrations, models
import django.db.models.deletion
import lib.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('account_user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'AccountUser/企業ユーザー',
                'verbose_name_plural': 'AccountUsers/企業ユーザー',
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', lib.fields.AutoCreatedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('updated_at', lib.fields.AutoLastModifiedField(db_index=True, default=lib.fields.unix_timestamp, editable=False)),
                ('live', lib.fields.IndexedLiveField(default=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_user_id', models.UUIDField(editable=False, unique=True)),
                ('full_name', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'User/ユーザー',
                'verbose_name_plural': 'Users/ユーザー',
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='user_user_id_31c9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['line_user_id'], name='user_line_us_4fd79b_idx'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id'], name='account_use_account_992007_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['user'], name='account_use_user_id_c25fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account'], name='account_use_account_9a5373_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountuser',
            unique_together={('user', 'account', 'live')},
        ),
    ]
