# Generated by Django 2.1.3 on 2018-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181210_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
