# Generated by Django 2.1.3 on 2018-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activity_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
