# Generated by Django 2.1.3 on 2018-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_activity_action_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
